### ISSUE TITLE
Make most used zones configurable

### ISSUE THREAD

**Issue by Pagebakers** [thespacedojo/timezone-picker#2]
Thanks for making this package, it's just what I needed.

Right now the most used zones (the ones on top of the list) are hardcoded to be US zones, however my app is targeted at European customers.

I would like to be able to configure these zones.

**Comment by queso** [comment]
I am happy to talk a pull request if you want to make this configurable
with the default being the US timezones that can be overridden.

**Comment by oliverlloyd** [comment]
+1 for making this configurable. Or just not opinionated at all.
